[project]
name = "simulations"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11, <3.13"
dependencies = [
    "cyvcf2>=0.34.0",
    "stdpopsim>=0.3.0",
    "tskit>=1.0.3",
    "malariagen-data @ git+https://github.com/malariagen/malariagen-data-python.git"
]

[project.scripts]
simulations = "simulations:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
